import { Car } from '../types';

// Seed data derived directly from scraped-content/occasions/*.md + cars-inventory-snapshot.json
// Use this for initial public rendering and development.
// In production replace with Supabase queries.

export const seedCars: Car[] = [
  {
    id: "c1",
    title: "Audi A1 1.2 TFSI Attraction 3DR |Apk |Lm velgen",
    slug: "audi-a1-3393770",
    brand: "Audi",
    model: "A1",
    version: "1.2 TFSI Attraction 3DR |Apk |Lm velgen",
    year: 2012,
    price: 4995,
    mileage: 233533,
    fuel_type: "Benzine",
    transmission: "Handmatig",
    body_type: "Hatchback",
    color: "Paars",
    doors: 3,
    seats: 4,
    power_hp: 86,
    apk_until: "2026-08-01",
    license_plate: "P988GG",
    vat_type: "Marge",
    status: "available",
    is_featured: true,
    main_image: "https://media-cdn.vwe.nl/Images/164669066.jpg",
    images: [
      { id: "c1-i1", car_id: "c1", image_url: "https://media-cdn.vwe.nl/Images/164669066.jpg", sort_order: 0, is_main: true },
      { id: "c1-i2", car_id: "c1", image_url: "https://media-cdn.vwe.nl/Images/164669067.jpg", sort_order: 1, is_main: false },
      { id: "c1-i3", car_id: "c1", image_url: "https://media-cdn.vwe.nl/Images/164669068.jpg", sort_order: 2, is_main: false },
      { id: "c1-i4", car_id: "c1", image_url: "https://media-cdn.vwe.nl/Images/164669069.jpg", sort_order: 3, is_main: false },
      { id: "c1-i5", car_id: "c1", image_url: "https://media-cdn.vwe.nl/Images/164669070.jpg", sort_order: 4, is_main: false },
    ],
    description: "Compacte en zuinige Audi A1 - ideaal voor de stad en het dagelijkse woon-werkverkeer. Netjes onderhouden, APK gekeurd en met een complete uitrusting. Een wendbare, betrouwbare instapper in een premium jasje.",
    options: [
      "Airbag bestuurder", "Airbag passagier", "Airbag(s) hoofd achter", "Airbag(s) hoofd voor",
      "Airbag(s) side voor", "Airco", "Anti Blokkeer Systeem (ABS)", "Armsteun voor",
      "Buitenspiegels elektrisch verstelbaar", "Centrale deurvergrendeling met afstandsbediening",
      "Cruise control", "Electronic Stability Program (ESP)", "Elektrische ramen voor",
      "Multimedia-voorbereiding", "Navigatie full map", "Radio-CD/MP3 speler", "Start/stop systeem",
      "Startblokkering", "Stuurbekrachtiging snelheidsafhankelijk", "Stuurwiel multifunctioneel",
      "Tractie Controle Systeem (TCS)", "Verwarmde voorstoelen"
    ],
  },
  {
    id: "c2",
    title: "BMW 3-serie 335i Business Line M Sport 306 PK |Nette staat",
    slug: "bmw-3-serie-3437096",
    brand: "BMW",
    model: "3-serie",
    version: "335i Business Line M Sport 306 PK |Nette staat",
    year: 2011,
    price: 13995,
    mileage: 217228,
    fuel_type: "Benzine",
    transmission: "Automaat",
    body_type: "Sedan",
    color: "Zwart",
    doors: 4,
    seats: 5,
    power_hp: 306,
    apk_until: "2026-07-05",
    license_plate: "44TKV6",
    vat_type: "Marge",
    status: "available",
    is_featured: true,
    main_image: "https://media-cdn.vwe.nl/Images/164669200.jpg",
    images: [
      { id: "c2-i1", car_id: "c2", image_url: "https://media-cdn.vwe.nl/Images/164669200.jpg", sort_order: 0, is_main: true },
      { id: "c2-i2", car_id: "c2", image_url: "https://media-cdn.vwe.nl/Images/164669203.jpg", sort_order: 1, is_main: false },
      { id: "c2-i3", car_id: "c2", image_url: "https://media-cdn.vwe.nl/Images/164669204.jpg", sort_order: 2, is_main: false },
      { id: "c2-i4", car_id: "c2", image_url: "https://media-cdn.vwe.nl/Images/164669205.jpg", sort_order: 3, is_main: false },
      { id: "c2-i5", car_id: "c2", image_url: "https://media-cdn.vwe.nl/Images/164669206.jpg", sort_order: 4, is_main: false },
    ],
    description: "Nette BMW 335i in goede staat. De auto is altijd met zorg behandeld en volledig onderhouden. Zowel technisch als optisch verkeert hij in nette conditie. De krachtige motor in combinatie met het comfortabele rijgedrag zorgt elke rit weer voor plezier, zowel bij rustig als sportief rijden.\n\nHet is een echte rijdersauto die strak op de weg ligt en soepel schakelt. Het interieur en exterieur zien er verzorgd uit, wat laat zien dat er goed op de auto is gelet. Geen afgetrapt exemplaar, maar een auto die duidelijk is gereden door een liefhebber.\n\nKortom: een complete en fijne BMW voor iemand die op zoek is naar rijplezier, comfort en vermogen in één. Instappen en genieten.",
    options: [
      "M Sport", "Bi-xenon", "Adaptieve cruise control", "Sportstoelen", "Leder bekleding",
      "Schuifdak", "18 inch velgen", "Navigatie", "Clima", "PDC", "Stoelverwarming"
    ],
  },
  {
    id: "c3",
    title: "Ford Galaxy 2.0 SCTi Titanium Automaat |7pers |Leer |Apk",
    slug: "ford-galaxy-3518938",
    brand: "Ford",
    model: "Galaxy",
    version: "2.0 SCTi Titanium Automaat |7pers |Leer |Apk",
    year: 2011,
    price: 1495,
    mileage: 318443,
    fuel_type: "Benzine",
    transmission: "Automaat",
    body_type: "MPV",
    color: "Grijs",
    doors: 5,
    seats: 7,
    power_hp: 203,
    apk_until: "2026-07-08",
    license_plate: "45PDT7",
    vat_type: "Marge",
    status: "available",
    is_featured: false,
    main_image: "https://media-cdn.vwe.nl/Images/170195043.jpg",
    images: [
      { id: "c3-i1", car_id: "c3", image_url: "https://media-cdn.vwe.nl/Images/170195043.jpg", sort_order: 0, is_main: true },
      { id: "c3-i2", car_id: "c3", image_url: "https://media-cdn.vwe.nl/Images/170195044.jpg", sort_order: 1, is_main: false },
      { id: "c3-i3", car_id: "c3", image_url: "https://media-cdn.vwe.nl/Images/170195045.jpg", sort_order: 2, is_main: false },
      { id: "c3-i4", car_id: "c3", image_url: "https://media-cdn.vwe.nl/Images/170195046.jpg", sort_order: 3, is_main: false },
      { id: "c3-i5", car_id: "c3", image_url: "https://media-cdn.vwe.nl/Images/170195047.jpg", sort_order: 4, is_main: false },
    ],
    description: "Let op Automaat bak niet goed!\nAuto rijdt en schakelt, automaat gaat in storing!!",
    options: ["7 persoons", "Leer", "Airco", "Trekhaak", "Cruise control"],
  },
  {
    id: "c4",
    title: "Mercedes-Benz B-klasse 170 Automaat |Apk",
    slug: "mercedes-benz-b-klasse-3653773",
    brand: "Mercedes",
    model: "B-klasse",
    version: "170 Automaat |Apk",
    year: 2007,
    price: 2795,
    mileage: 219440,
    fuel_type: "Benzine",
    transmission: "Automaat",
    body_type: "MPV",
    color: "Grijs",
    doors: 5,
    seats: 5,
    power_hp: 116,
    apk_until: "2026-10-21",
    license_plate: "23ZRBS",
    vat_type: "Marge",
    status: "available",
    is_featured: true,
    main_image: "https://media-cdn.vwe.nl/Images/170195100.jpg",
    images: [
      { id: "c4-i1", car_id: "c4", image_url: "https://media-cdn.vwe.nl/Images/170195100.jpg", sort_order: 0, is_main: true },
      { id: "c4-i2", car_id: "c4", image_url: "https://media-cdn.vwe.nl/Images/170195101.jpg", sort_order: 1, is_main: false },
      { id: "c4-i3", car_id: "c4", image_url: "https://media-cdn.vwe.nl/Images/170195102.jpg", sort_order: 2, is_main: false },
      { id: "c4-i4", car_id: "c4", image_url: "https://media-cdn.vwe.nl/Images/170195103.jpg", sort_order: 3, is_main: false },
      { id: "c4-i5", car_id: "c4", image_url: "https://media-cdn.vwe.nl/Images/170195105.jpg", sort_order: 4, is_main: false },
    ],
    description: "Auto heeft rondom beschadigingen.",
    options: ["Airco", "Cruise control", "Automaat"],
  },
  {
    id: "c5",
    title: "Audi A6 Avant 2.0 TFSI Business Edition Automaat |Nap |Apk",
    slug: "audi-a6-avant-3574299",
    brand: "Audi",
    model: "A6",
    version: "Avant 2.0 TFSI Business Edition Automaat |Nap |Apk",
    year: 2014,
    price: 13950,
    mileage: 203259,
    fuel_type: "Benzine",
    transmission: "Automaat",
    body_type: "Stationwagen",
    color: "Zilver",
    doors: 5,
    seats: 5,
    power_hp: 180,
    apk_until: "2026-06-30",
    vat_type: "Marge",
    status: "available",
    is_featured: false,
    main_image: "https://media-cdn.vwe.nl/Images/placeholder-a6.jpg",
    description: "Ruime en comfortabele Audi A6 Avant. Goed onderhouden en klaar voor gebruik.",
    options: ["Navigatie", "Clima", "Cruise", "Trekhaak", "PDC"],
  },
  {
    id: "c6",
    title: "Opel Corsa 1.2-16V BlitZ Apk |Airco |Cruise",
    slug: "opel-corsa-3658161",
    brand: "Opel",
    model: "Corsa",
    version: "1.2-16V BlitZ Apk |Airco |Cruise",
    year: 2014,
    price: 1995,
    mileage: 261633,
    fuel_type: "Benzine",
    transmission: "Handmatig",
    body_type: "Hatchback",
    color: "Rood",
    doors: 5,
    seats: 5,
    power_hp: 70,
    apk_until: "2026-09-15",
    vat_type: "Marge",
    status: "available",
    is_featured: false,
    main_image: "https://media-cdn.vwe.nl/Images/placeholder-corsa.jpg",
    description: "Kleine zuinige en betrouwbare auto. Ideaal voor stad en korte afstanden. APK gekeurd en goed onderhouden.",
    options: ["Airco", "Cruise control"],
  },
  {
    id: "c7",
    title: "Ford C-Max 1.8-16V Limited Nap |Apk |Trekhaak",
    slug: "ford-c-max-3490128",
    brand: "Ford",
    model: "C-Max",
    version: "1.8-16V Limited Nap |Apk |Trekhaak",
    year: 2009,
    price: 2995,
    mileage: 189638,
    fuel_type: "Benzine",
    transmission: "Handmatig",
    body_type: "MPV",
    color: "Blauw",
    doors: 5,
    seats: 5,
    power_hp: 125,
    apk_until: "2026-05-20",
    vat_type: "Marge",
    status: "reserved",
    is_featured: false,
    main_image: "https://media-cdn.vwe.nl/Images/placeholder-cmax.jpg",
    description: "Ruime gezinswagen. Gereserveerd.",
    options: ["Trekhaak", "Airco", "Cruise", "Nap"],
  },
  {
    id: "c8",
    title: "Volkswagen Fox 1.4 Trendline Apk |Nap |Hoogzit",
    slug: "volkswagen-fox-3658169",
    brand: "Volkswagen",
    model: "Fox",
    version: "1.4 Trendline Apk |Nap |Hoogzit",
    year: 2007,
    price: 2295,
    mileage: 120377,
    fuel_type: "Benzine",
    transmission: "Handmatig",
    body_type: "Hatchback",
    color: "Zilver",
    doors: 3,
    seats: 4,
    power_hp: 75,
    apk_until: "2026-08-10",
    vat_type: "Marge",
    status: "available",
    is_featured: false,
    main_image: "https://media-cdn.vwe.nl/Images/placeholder-fox.jpg",
    description: "Compacte en zuinige Volkswagen. Goede instapauto.",
    options: ["Hoogzit", "Nap", "Apk"],
  },
];

export function getFeaturedCars(): Car[] {
  return seedCars.filter(c => c.is_featured && c.status === 'available').slice(0, 6);
}

export function getAvailableCars(): Car[] {
  return seedCars.filter(c => c.status === 'available' || c.status === 'reserved');
}
